name: live_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  responsive_framework: ^1.5.1
  form_builder_validators: ^11.0.0
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  image_picker_for_web:
  image_picker:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
