class EndPoints {
  const EndPoints._();

  static const String baseUrl = 'https://iptv.sunilflutter.in/api/';
  static const String login = "admin/login";
  static const String user = "userdata";

  static const Duration timeout = Duration(seconds: 30);

  static const String token = 'authToken';
}

enum LoadDataState { initialize, loading, loaded, error, timeout, unknownerror }

List<String> movieCategories = [
  "Action",
  "Adventure",
  "Animation",
  "Biography",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Family",
  "Fantasy",
  "History",
  "Horror",
  "Musical",
  "Mystery",
  "Romance",
  "Science Fiction",
  "Sport",
  "Thriller",
  "War",
  "Western",
  "Superhero",
  "Noir",
  "Independent",
  "Disaster",
  "Historical Fiction",
  "Parody",
  "Epic",
  "Political",
  "Psychological",
  "Survival",
  "Slasher",
  "Dark Comedy",
  "Coming of Age",
  "Heist",
  "Spy",
  "Time Travel",
  "Cyberpunk",
  "Steampunk",
  "Space Opera",
  "Martial Arts",
  "Post-Apocalyptic",
  "Zombie",
  "Creature Feature",
  "Religious",
  "Detective",
  "Legal/Justice",
  "Romantic Comedy",
  "Satire",
  "Fantasy Adventure",
  "Science Fantasy",
  "War Drama",
  "Sword and Sorcery",
  "Road Movie",
  "Anthology",
  "Vampire",
  "Werewolf",
  "Supernatural Horror",
];
List<String> movieTypes = [
  "Feature Film",
  "Short Film",
  "Documentary",
  "Series",
  "TV Show",
  "Mini-Series",
  "Animated Film",
  "Anthology",
  "Silent Film",
  "Stop-Motion Film",
  "3D Film",
  "Live-Action",
  "Mockumentary",
  "Web Series",
  "Experimental Film",
  "Musical Film",
  "Biography Film",
  "IMAX",
  "Direct-to-Video",
  "Streaming Exclusive",
  "Indie Film",
  "Made-for-TV",
  "Foreign Film",
  "Arthouse Film",
  "Blockbuster",
  "Fan Film",
  "Reboot",
  "Sequel",
  "Prequel",
  "Spin-off",
  "Found Footage",
  "Adaptation",
  "Docudrama",
  "Docuseries",
  "Reality Show",
  "Stage-to-Screen",
  "Motion Capture",
  "Interactive Film",
  "Children’s Film",
  "Holiday Film",
  "Film Noir",
  "Silent Film",
  "Satirical Film",
  "Claymation",
  "Animated Short",
  "Director’s Cut",
  "Supercut",
  "Compilation Film",
  "Travelogue",
];
